### PR TITLE
JBTIS-1026: Extend and use runtime annotation

### PR DESCRIPTION
**Pull request by domhanak**
This adds necessarry classes for Runtime annotation to be usable.
Adds handler for Jbpm Runtime Preference page and its Wizard.
Adds an option to distinquish between MVN and RUNTIME options
in new  project setup wizard and makes use of Runtime annotation
to handle runtime setup.

### CODE REVIEW

**Comment by apodhrad** [comment]
Can one of the admins verify this patch?

**Comment by apodhrad** [comment]
Is this PR ready to merge?

**Comment by tsedmik** [comment]
Is this PR ready to merge?

**Comment by tsedmik** [comment]
@domhanak If a pull request is not ready for merge, add _dev__ prefix to name of the PR. Once the PR is ready just remove the prefix and we will review and merge it.

**Comment by domhanak** [comment]
@tsedmik sure will do in future

**Comment by domhanak** [comment]
Ready to merge.
@apodhrad or @jomarko should review before merging

**Comment by apodhrad** [comment]
test this please

**Comment by domhanak** [comment]
test this please

**Comment by apodhrad** [comment]
test this please

**Comment by apodhrad** [comment]
pushed to master

**Comment by domhanak** [comment]
test this please

**Comment by tsedmik** [comment]
closing - already in master

**Pull request closed without merging**
