### PR TITLE
Runtime: Fix problem with 'New Server' wizard

### PR DESCRIPTION
**Pull request by tsedmik**
New Server wizard sometimes loses focus

### CODE REVIEW

**Comment by tsedmik** [comment]
please merge the fix also into _jbtis-4.2.x_ branch.

**Comment by tsedmik** [comment]
_note: originates from #243_

**Comment by tsedmik** [comment]
still hit the problem ... need to investigate

**Comment by tsedmik** [comment]
looks good now. Please merge the fix also into jbtis-4.2.x branch.

**Comment by tsedmik** [comment]
test this

**Comment by apodhrad** [comment]
pushed to master and jbtis-4.2.x

**Pull request merged**
