### PR TITLE
Teiid: Fix Import Tests

### PR DESCRIPTION
**Pull request by mmakovy**

### CODE REVIEW

**Comment by mmakovy** [comment]
please, push this also to jbtis-4.2.x branch

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by tsedmik** [comment]
test this

**Comment by tsedmik** [comment]
looking

**Comment by tsedmik** [comment]
pushed to _master_ and _jbtis-4.2.x_ branch

**Pull request merged**
