### PR TITLE
JBTIS-758: Add test for collapse/expand feature in Camel Editor

### PR DESCRIPTION
**Pull request by djelinek**

### CODE REVIEW

**Comment by apodhrad** [comment]
the verification job has failed due to
```
Error Message

expected:<34> but was:<228>

Stacktrace

java.lang.AssertionError: expected:<34> but was:<228>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.jboss.tools.fuse.ui.bot.test.CamelEditorTest.testCollapseExpandFeature(CamelEditorTest.java:291)
```

**Comment by tsedmik** [comment]
test this please

**Comment by apodhrad** [comment]
test this please

**Comment by tsedmik** [comment]
test this please

**Comment by djelinek** [comment]
test passed on fedora25, win10 and mac, but only on fedora24 (verification job) it still fails

**Comment by tsedmik** [comment]
test this please

**Comment by tsedmik** [comment]
It works well on Fedora 25. I suggest to wait with this PR. Support for Fedora 24 will end on July ;-)

**Comment by tsedmik** [comment]
test this please

**Comment by tsedmik** [comment]
@djelinek please rebase this PR to master branch (to get actual state of tests)

**Comment by djelinek** [comment]
Migrate to FUSETOOLS

**Pull request closed without merging**
