### PR TITLE
Teiid: Add test capability to force quotes around the column names containing spaces

### PR DESCRIPTION
**Pull request by mkralik3**
Add test which test that the name containing spaces in "Name in Source" is set properly
To the previewModel test was added preview table which contains name with spaces
To the JDBCImportWizardTest was added function which test that the columns name in "Name in Source" is set properly.

### CODE REVIEW

**Comment by mkralik3** [comment]
please push this also to jbtis-4.2.x branch

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by tsedmik** [comment]
test this

**Comment by tsedmik** [comment]
pushed to _master_ and _jbtis-4.2.x_ branch

**Pull request merged**
