### PR TITLE
JBTIS-985 - Fuse: Fix smoke tests

### PR DESCRIPTION
**Pull request by tsedmik**
https://issues.jboss.org/browse/JBTIS-985

### CODE REVIEW

**Comment by tsedmik** [comment]
test this please

**Comment by tsedmik** [comment]
test this please

**Comment by apodhrad** [comment]
@tsedmik is this PR ready to be merged? The verification job has passed ;-)

**Comment by tsedmik** [comment]
@apodhrad yes ... please merge it :-)

**Comment by apodhrad** [comment]
pushed to master

**Pull request closed without merging**
