### PR TITLE
Drools: Add Kie navigator tests to Brms6TestSuite

### PR DESCRIPTION
**Pull request by tomasdavidorg**

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by apodhrad** [comment]
do you want to push it also to jbtis-4.2.x?

**Comment by tomasdavidorg** [comment]
No, it's not necessary. Thanks.

**Comment by apodhrad** [comment]
pushed to master

**Pull request closed without merging**
