### PR TITLE
BPMN2: do not use DefaultShell() everywhere

### PR DESCRIPTION
**Pull request by jomarko**
During setting properties via graphiti properties view, DefaultShell() returns wrong shell, it is needed to use DefaultShell(label);

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch?

**Comment by tsedmik** [comment]
test this

**Comment by apodhrad** [comment]
please remove the commented code

**Comment by jomarko** [comment]
sorry for that, comments should be removed now

**Pull request merged**
