### PR TITLE
Teiid: Improve TeiidJDBCHelper and refactor tests to use this class

### PR DESCRIPTION
**Pull request by mmakovy**

### CODE REVIEW

**Comment by tsedmik** [comment]
test this

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by apodhrad** [comment]
please remove the code which is commented out

**Comment by mmakovy** [comment]
I removed the code that was commented out in TeiidBot.java

**Comment by apodhrad** [comment]
pushed to master

@mmakovy: would you like to have it on luna branch (jbtis-4.2.x)?

**Comment by mmakovy** [comment]
@apodhrad yes, that would be great. Thanks

**Comment by apodhrad** [comment]
Unfortunately, there are lots of problems with applying your patch to the branch jbtis-4.2.x, It seems that that there were pull requests which were pushed only to the master branch and not the the jbtis-4.2.x.

Please create a new pull request for the branch jbtis-4.2.x.

**Pull request closed without merging**
