### PR TITLE
Runtime: Extend XSD Schema 

### PR DESCRIPTION
**Pull request by apodhrad**
Extend XSD Schema
    * Karaf - add version 2.4 and 3.0
    * add support for Apache ServiceMix 4.5 and Apache ServiceMix 5.0_
    * add support for Fabric8 1.1

### CODE REVIEW

**Comment by apodhrad** [comment]
pushed to master

**Comment by tsedmik** [comment]
_server-requirement_ should be extended too. Not only _switchyard-requirement_.

**Comment by apodhrad** [comment]
tomorrow it should be available at http://www.jboss.org/schema/reddeer/3rdparty/SOARequirements.xsd

**Comment by tsedmik** [comment]
pushed to master

**Pull request closed without merging**
