### PR TITLE
JBTIS-1006: SY - Allow skipping maven settings

### PR DESCRIPTION
**Pull request by apodhrad**

### CODE REVIEW

**Comment by tsedmik** [comment]
A lot of failed tests were occurred in verification job. Please investigate them.

**Comment by apodhrad** [comment]
The reason is a bug the the SwitchYard tooling reported at https://issues.jboss.org/browse/SWITCHYARD-2986 and has nothing in common with this PR

**Comment by apodhrad** [comment]
please do no merge this PR at this moment

**Comment by apodhrad** [comment]
test this please

**Comment by apodhrad** [comment]
test this please

**Comment by apodhrad** [comment]
test this please

**Comment by apodhrad** [comment]
test this please

**Comment by apodhrad** [comment]
test this please

**Comment by apodhrad** [comment]
test this please

**Comment by apodhrad** [comment]
test this please

**Comment by apodhrad** [comment]
test this please

**Comment by apodhrad** [comment]
ready to merge

**Pull request merged**
