### PR TITLE
JBTIS-612 Remove DynamicVDB Test from AllTests

### PR DESCRIPTION
**Pull request by mmakovy**
https://issues.jboss.org/browse/JBTIS-612

### CODE REVIEW

**Comment by mmakovy** [comment]
please, push this also to jbtis-4.2.x branch

**Comment by vpakan** [comment]
Can one of the admins verify this patch?

**Comment by tsedmik** [comment]
test this

**Comment by apodhrad** [comment]
pushed to master

**Comment by apodhrad** [comment]
pushed to jbtis-4.2.x as well

**Pull request closed without merging**
