### PR TITLE
BPMN2: use PropertiesView

### PR DESCRIPTION
**Pull request by jomarko**
Replace old DefaultPropertiesView with official PropertiesView: https://github.com/jboss-reddeer/reddeer/blob/master/plugins/org.jboss.reddeer.eclipse/src/org/jboss/reddeer/eclipse/ui/views/properties/PropertiesView.java

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch?

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
pushed to master

**Pull request closed without merging**
