### PR TITLE
Drools: Fix selectPage() wizard issue

### PR DESCRIPTION
**Pull request by tomasdavidorg**

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
pushed to master and jbtis-4.3.x

**Pull request merged**
