### PR TITLE
Add and split JDBC and Teiid import tests and import DTF tests

### PR DESCRIPTION
**Pull request by mmajerni**

### CODE REVIEW

**Comment by mmajerni** [comment]
Please wait I am doing tiny changes

**Comment by tsedmik** [comment]
test this please

**Comment by apodhrad** [comment]
@mmajerni is this PR ready to be merged?

**Comment by mmajerni** [comment]
@apodhrad yes it is

**Comment by apodhrad** [comment]
pushed to master

**Pull request closed without merging**
