### PR TITLE
Merge latest Teiid changes

### PR DESCRIPTION
**Pull request by asmigala**

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by tsedmik** [comment]
test this

**Comment by apodhrad** [comment]
* Why there is the class Base64? Isn't it in java.util package?
* The PR contains binary files *.vdb, can we get rid of using binary files? e.g. can we generate th vdb files?

**Comment by asmigala** [comment]
Force pushed new set of commits without the binary files.
Base64 is included in java.util only since 1.8, that's why I used a public-domain version from iharder.net/base64

**Pull request merged**
