### PR TITLE
Teiid: Fix 'ModelWizardTest'

### PR DESCRIPTION
**Pull request by mmakovy**
The following error affects our verification job.

**Error Message**

Menu item is not enabled

**Stacktrace**
```
org.jboss.reddeer.core.exception.CoreLayerException: Menu item is not enabled
	at org.jboss.reddeer.core.handler.MenuHandler.select(MenuHandler.java:92)
	at org.jboss.reddeer.swt.impl.menu.ShellMenu.select(ShellMenu.java:72)
	at org.jboss.tools.teiid.ui.bot.test.ModelWizardTest.saveAllFiles(ModelWizardTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.jboss.reddeer.junit.internal.runner.statement.RunAfters.evaluate(RunAfters.java:66)
	at org.jboss.reddeer.junit.internal.runner.statement.CleanUpRequirementStatement.evaluate(CleanUpRequirementStatement.java:34)
	at org.jboss.reddeer.junit.internal.runner.statement.RunIAfterClassExtensions.evaluate(RunIAfterClassExtensions.java:48)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.jboss.reddeer.junit.internal.runner.RequirementsRunner.run(RequirementsRunner.java:146)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:156)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:82)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:91)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:44)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable$1.run(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:745)
```

**Standard Output**
```
14:05:12.284 INFO [WorkbenchTestable][RequirementsRunner] Finished test: relationalSourceModel as-711_teiid-830.xml(org.jboss.tools.teiid.ui.bot.test.ModelWizardTest)
14:05:22.284 DEBUG [WorkbenchTestable][AbstractWait] Waiting until active shell exists...
14:05:22.284 DEBUG [WorkbenchTestable][AbstractWait] Waiting until active shell exists finished successfully
14:05:22.285 INFO [main][MenuLookup] Getting Menu Bar of shell 'Teiid Designer - ModelWizardTestProject/relational_source.xmi - '
14:05:22.289 DEBUG [main][MenuLookup] Found menu:'File'
14:05:22.289 DEBUG [main][MenuLookup] Item match:File
14:05:22.293 DEBUG [main][MenuLookup] Found menu:'New	Shift+Alt+N'
14:05:22.293 DEBUG [main][MenuLookup] Found menu:'Open File...'
14:05:22.293 DEBUG [main][MenuLookup] Found menu:''
14:05:22.293 DEBUG [main][MenuLookup] Found menu:'Close	Ctrl+W'
14:05:22.293 DEBUG [main][MenuLookup] Found menu:'Close All	Shift+Ctrl+W'
14:05:22.293 DEBUG [main][MenuLookup] Found menu:''
14:05:22.293 DEBUG [main][MenuLookup] Found menu:'Save	Ctrl+S'
14:05:22.293 DEBUG [main][MenuLookup] Found menu:'Save As...'
14:05:22.293 DEBUG [main][MenuLookup] Found menu:'Save All	Shift+Ctrl+S'
14:05:22.293 DEBUG [main][MenuLookup] Item match:Save All	Shift+Ctrl+S
14:05:22.294 DEBUG [WorkbenchTestable][MenuHandler] Queried MenuItem text:"Sav&e All	Shift+Ctrl+S"
14:05:22.294 INFO [WorkbenchTestable][ShellMenu] Select shell menu with text Sav&e All	Shift+Ctrl+S
14:05:22.294 DEBUG [main][Display] UI Call chaining attempt
14:05:22.299 DEBUG [main][ScreenshotCapturer] Capturing Screenshot: ./target/screenshots/as-711_teiid-830.xml/org.jboss.tools.teiid.ui.bot.test.ModelWizardTest.saveAllFiles@AfterClass.png
14:05:22.461 DEBUG [main][ScreenshotCapturer] Screenshot successfully captured. Saved in /home/jbossqa/workspace/jbtis43x.verification.job/tests/org.jboss.tools.teiid.ui.bot.test/./target/screenshots/as-711_teiid-830.xml/org.jboss.tools.teiid.ui.bot.test.ModelWizardTest.saveAllFiles@AfterClass.png
14:05:22.461 DEBUG [WorkbenchTestable][RunIAfterClassExtensions] Run after class extensions for test class org.jboss.tools.teiid.ui.bot.test.ModelWizardTest
14:05:22.461 DEBUG [WorkbenchTestable][RunIAfterClassExtensions] Run method runAfterTestClass() of class org.jboss.reddeer.junit.extension.after.test.impl.CloseAllShellsExt
14:05:22.461 INFO [WorkbenchTestable][ShellHandler] Closing all shells...
14:05:22.463 DEBUG [WorkbenchTestable][AbstractWait] Waiting until active shell exists...
14:05:22.463 DEBUG [WorkbenchTestable][AbstractWait] Waiting until active shell exists finished successfully
```

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by mmakovy** [comment]
Please, merge this also into jbtis-4.2.x branch

**Comment by tsedmik** [comment]
ok to test

**Comment by tsedmik** [comment]
looking

**Comment by tsedmik** [comment]
pushed to _master_ and _jbtis-4.2.x_ branch

**Pull request closed without merging**
