### PR TITLE
Teiid: Add CloneAndCopyTest and XmlSchemalessTest

### PR DESCRIPTION
**Pull request by StanleyKaleta**

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by apodhrad** [comment]
test this

**Comment by mmakovy** [comment]
please, push it also to jbtis-4.2.x branch

**Comment by apodhrad** [comment]
pushed to master and jbtis-4.2.x

**Pull request merged**
