### PR TITLE
Teiid: Clean up test suites

### PR DESCRIPTION
**Pull request by mmakovy**

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by mmakovy** [comment]
please push this also to jbtis-4.2.x branch

**Comment by tsedmik** [comment]
test this

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
pushed to master and jbtis-4.2.x

**Pull request closed without merging**
