### PR TITLE
JBTIS-882: Fuse - Create a general DeploymentTest which will work wit…

### PR DESCRIPTION
**Pull request by tsedmik**
…h Fuse and FuseOnEAP

https://issues.jboss.org/browse/JBTIS-882

Signed-off-by: Tomáš Sedmík <tsedmik@redhat.com>

### CODE REVIEW

**Comment by tsedmik** [comment]
test this please

**Comment by apodhrad** [comment]
The test is still failing
```
testServerDeployment fuse-630.xml(org.jboss.tools.fuse.ui.bot.test.DeploymentTest)  Time elapsed: 39.349 sec  <<< FAILURE!
java.lang.AssertionError: The project was not properly deployed!
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.jboss.tools.fuse.ui.bot.test.DeploymentTest.testServerDeployment(DeploymentTest.java:136)
```

**Comment by apodhrad** [comment]
Sometimes happens that there are two projects
- project
- project (camel-test-spring)

The first one doesn't work (I have no idea why the project is listed) and the second one works fine (but the test takes the first one).

**Comment by tsedmik** [comment]
That is strange. I tried it once again and it works. Look at the following test runs:
* https://jbdsis-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Fuse%20Tooling/job/devstudio-11-fuse-matrix/10/
* https://jbdsis-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Fuse%20Tooling/job/devstudio-11-fuse-matrix/9/

**Comment by tsedmik** [comment]
test this please

**Comment by apodhrad** [comment]
pushed to master

**Pull request closed without merging**
