### PR TITLE
JBTIS-685 - Clean-up resources folder

### PR DESCRIPTION
**Pull request by mmakovy**
https://issues.jboss.org/browse/JBTIS-685

### CODE REVIEW

**Comment by mmakovy** [comment]
test this

**Comment by apodhrad** [comment]
the verification job has failed due to 
```
The configuration location /home/jbossqa/workspace/jbtis43x.verification.job/tests/org.jboss.tools.teiid.ui.bot.test/target/config/as-711_teiid-830.xml does not exist
```

**Comment by mmakovy** [comment]
test this

**Comment by apodhrad** [comment]
pushed to master

**Pull request closed without merging**
