### PR TITLE
Drools: Improve drools tests stability

### PR DESCRIPTION
**Pull request by tomasdavidorg**

### CODE REVIEW

**Comment by tomasdavidorg** [comment]
Merge these commits to master and jbtis-4.2.x. Thanks.

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
Please merge your commits to the only one.

**Comment by tomasdavidorg** [comment]
@apodhrad Is it ok to do it this way?

**Comment by apodhrad** [comment]
pushed to master and jbtis-4.2.x

**Pull request closed without merging**
