### PR TITLE
BPMN2: new concept - PropertiesHandler

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch?

**Comment by apodhrad** [comment]
- there are lots of lines which are commented out, remove unwanted code
- extract constants to one class, e.g. Task.UserTask, Task.CallActivity

**Comment by jomarko** [comment]
* Removed commented lines
* Used LabeledCheckBox from RedDeer7
* Created constants for tab labels in Properties view of BPMN modeler

**Comment by apodhrad** [comment]
retest this please

**Comment by jomarko** [comment]
Smoke tests passed: http://machydra.brq.redhat.com:8080/view/JBTIS%204.2.x%20Bot%20Tests/job/jbdsis8x.custom.test/14/

**Pull request merged**
