### PR TITLE
Drools: project wizard and runtime tests updates

### PR DESCRIPTION
**Pull request by tomasdavidorg**

### CODE REVIEW

**Comment by tomasdavidorg** [comment]
test this

**Comment by apodhrad** [comment]
The verification test has failed with the following result

Error Message

Timeout after: 10 s.: Tests that currently running application is in terminated state

Stacktrace

org.jboss.reddeer.common.exception.WaitTimeoutExpiredException: Timeout after: 10 s.: Tests that currently running application is in terminated state
	at org.jboss.reddeer.common.wait.AbstractWait.timeoutExceeded(AbstractWait.java:173)
	at org.jboss.reddeer.common.wait.AbstractWait.wait(AbstractWait.java:126)
	at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:91)
	at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:61)
	at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:46)
	at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:34)
	at org.jboss.reddeer.common.wait.WaitUntil.<init>(WaitUntil.java:25)
	at org.jboss.tools.drools.ui.bot.test.functional.MavenProjectTest.createMavenProjectTest(MavenProjectTest.java:35)

**Comment by tomasdavidorg** [comment]
test this

**Comment by apodhrad** [comment]
Unfortunately, the tests are still failing. It seems that the tests are failing only if executing from cmd (from jbds the pass).

**Comment by tomasdavidorg** [comment]
test this

**Comment by tomasdavidorg** [comment]
test this

**Comment by apodhrad** [comment]
pushed to master

**Pull request closed without merging**
