### PR TITLE
JBTIS-1021: Correct AllWizardsTest suite

### PR DESCRIPTION
**Pull request by domhanak**
**[Mergable]**
Correct process and project wizards test

This commit changes handling logic to reflect UI changes and also
corrects some minor errors, that prevented these tests from giving correct
results.

### CODE REVIEW

**Comment by apodhrad** [comment]
Can one of the admins verify this patch?

**Comment by domhanak** [comment]
@jomarko please take a look at this

**Comment by jomarko** [comment]
@domhanak please rebase your branch with the latest master commit.

**Comment by tsedmik** [comment]
Is this PR ready for merge?

**Comment by jomarko** [comment]
hi @tsedmik yes, it is ready for merge

**Comment by tsedmik** [comment]
test this please

**Comment by tsedmik** [comment]
test this please

**Comment by tsedmik** [comment]
PR was pushed to master

**Pull request closed without merging**
