### PR TITLE
Fuse: Use new Maven repo for FuseProjectTest

### PR DESCRIPTION
**Pull request by tsedmik**
new maven repo with no settings.xml file should be used with this test

### CODE REVIEW

**Comment by apodhrad** [comment]
There is the following error

Timeout after: 300 s.: console contains 'Starting Camel ...'
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building A Camel Spring Route 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ camel-spring ---
[INFO] Deleting /home/jbossqa/workspace/jbtis43x.verification.job/tests/org.jboss.tools.fuse.ui.bot.test/target/work/data/camel-spring/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ camel-spring ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ camel-spring ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ camel-spring ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:testCompile (default-testCompile) @ camel-spring ---
[INFO] Compiling 1 source file to /home/jbossqa/workspace/jbtis43x.verification.job/tests/org.jboss.tools.fuse.ui.bot.test/target/work/data/camel-spring/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ camel-spring ---
[INFO] Surefire report directory: /home/jbossqa/workspace/jbtis43x.verification.job/tests/org.jboss.tools.fuse.ui.bot.test/target/work/data/camel-spring/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.mycompany.camel.spring.CamelContextXmlTest
[                          main] CamelContextXmlTest            INFO  ********************************************************************************
[                          main] CamelContextXmlTest            INFO  Testing: testCamelRoute(com.mycompany.camel.spring.CamelContextXmlTest)
[                          main] CamelContextXmlTest            INFO  ********************************************************************************
[                          main] DefaultTypeConverter           INFO  Loaded 183 type converters
[                          main] SpringCamelContext             INFO  Apache Camel 2.15.1.redhat-620133 (CamelContext: camel-1) is starting
[                          main] ManagedManagementStrategy      INFO  JMX is enabled
[                          main] SpringCamelContext             INFO  AllowUseOriginalMessage is enabled. If access to the original message is not needed, then its recommended to turn this option off as it may improve performance.
[                          main] SpringCamelContext             INFO  StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
[                          main] FileEndpoint                   INFO  Endpoint is configured with noop=true so forcing endpoint to be idempotent as well
[                          main] FileEndpoint                   INFO  Using default memory based idempotent repository with cache max size: 1000
[                          main] XPathBuilder                   INFO  Created default XPathFactory com.sun.org.apache.xpath.internal.jaxp.XPathFactoryImpl@30d4b288
[                          main] SpringCamelContext             INFO  Route: route1 started and consuming from: Endpoint[file://src/data?noop=true]
[                          main] SpringCamelContext             INFO  Total 1 routes, of which 1 is started.
[                          main] SpringCamelContext             INFO  Apache Camel 2.15.1.redhat-620133 (CamelContext: camel-1) started in 0.628 seconds
[                          main] CamelContextXmlTest            INFO  ********************************************************************************
[                          main] CamelContextXmlTest            INFO  Testing done: testCamelRoute(com.mycompany.camel.spring.CamelContextXmlTest)
[                          main] CamelContextXmlTest            INFO  Took: 0.000 seconds (0 millis)
[                          main] CamelContextXmlTest            INFO  ********************************************************************************
[                          main] SpringCamelContext             INFO  Apache Camel 2.15.1.redhat-620133 (CamelContext: camel-1) is shutting down
[                          main] DefaultShutdownStrategy        INFO  Starting to graceful shutdown 1 routes (timeout 10 seconds)
[el-1) thread #1 - ShutdownTask] DefaultShutdownStrategy        INFO  Route: route1 shutdown complete, was consuming from: Endpoint[file://src/data?noop=true]
[                          main] DefaultShutdownStrategy        INFO  Graceful shutdown of 1 routes completed in 0 seconds
[                          main] SpringCamelContext             INFO  Apache Camel 2.15.1.redhat-620133 (CamelContext: camel-1) uptime 0.647 seconds
[                          main] SpringCamelContext             INFO  Apache Camel 2.15.1.redhat-620133 (CamelContext: camel-1) is shutdown in 0.009 seconds
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.262 sec <<< FAILURE!
testCamelRoute(com.mycompany.camel.spring.CamelContextXmlTest)  Time elapsed: 3.085 sec  <<< FAILURE!
java.lang.AssertionError
 at org.junit.Assert.fail(Assert.java:86)
 at org.junit.Assert.fail(Assert.java:95)
 at com.mycompany.camel.spring.CamelContextXmlTest.testCamelRoute(CamelContextXmlTest.java:32)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
 at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
 at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
 at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
 at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
 at org.junit.rules.RunRules.evaluate(RunRules.java:20)
 at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
 at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
 at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
 at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
 at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
 at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
 at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
 at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
 at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
 at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
 at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
 at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
 at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
 at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by tsedmik** [comment]
the problem was resolved

**Comment by tsedmik** [comment]
test this

**Comment by apodhrad** [comment]
pushed to master

**Pull request closed without merging**
