### PR TITLE
JBTIS-647 Add test for Swagger

### PR DESCRIPTION
**Pull request by mmakovy**
https://issues.jboss.org/browse/JBTIS-647

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch?

**Comment by mmakovy** [comment]
test this

**Comment by mmakovy** [comment]
test this

**Comment by tsedmik** [comment]
test this

**Comment by apodhrad** [comment]
There is a problem with resolving the GSON dependency. The fastest solution is removing the version restriction or setting it to 2.1.0. 
From some reason there is only GSON 2.1.0 available in the build. I will investigate what's wrong here.

Moreover, please be careful with auto formatting pom.xml.

**Comment by mmakovy** [comment]
test this

**Comment by mmakovy** [comment]
test this

**Comment by apodhrad** [comment]
pushed to master

**Pull request closed without merging**
