### PR TITLE
Drools: Add temporary test suite without Kie Navigator tests

### PR DESCRIPTION
**Pull request by tomasdavidorg**

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by tsedmik** [comment]
looking

**Comment by tsedmik** [comment]
pushed to master
+ added new line at the end of file

**Pull request closed without merging**
