### PR TITLE
Teiid: Reflect important changes from jbtis-4.2.x branch to master

### PR DESCRIPTION
**Pull request by mmakovy**

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by tsedmik** [comment]
test this

**Comment by apodhrad** [comment]
@mmakovy please rebase it on master

**Comment by apodhrad** [comment]
@mmakovy please take into account issues #570 and #575

**Comment by mmakovy** [comment]
I'll close this PR and submit a new one later, because of other changes in our part of the code.

**Comment by apodhrad** [comment]
@mmakovy you can always use force push ;-)

**Pull request closed without merging**
