### PR TITLE
BPMN2: addapted tests for jbdsis-8.0.5 #589

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by tsedmik** [comment]
ok to test

**Comment by tsedmik** [comment]
looking

**Comment by tsedmik** [comment]
This pull request seems to be duplicate to #589  (see issue references in the pull request title). Am I right? Please, correct it.

**Comment by jomarko** [comment]
@tsedmik I am not sure what should I fix, this PR is solving #589 issue

**Comment by tsedmik** [comment]
pushed to _jbtis-4.2.x_ branch

**Comment by tsedmik** [comment]
@jomarko there is no need to create a new pull request(issue) for an fixed issue. Issues can be transformed to PR see https://github.com/jbosstools/jbosstools-integration-stack-tests#howtocontribute

**Comment by jomarko** [comment]
@tsedmik oh, sorry, I haven't contributed to this repo for a longer time. I have totally forgotten about @apodhrad scripts.

**Pull request closed without merging**
