### PR TITLE
Teiid: connection profiles moved to class annotation

### PR DESCRIPTION
**Pull request by jstastny-cz**
RestCallTest updated test and artifacts
XmlFileImportTest created
ServerMgmtTest.zip removed connection information from source model
updated matchers (labels, titles,..)

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch?

**Comment by apodhrad** [comment]
retest this please

**Comment by apodhrad** [comment]
Remove binary files from this pull request, please

**Comment by apodhrad** [comment]
when you are done, please remove the prefix "dev_"

**Comment by apodhrad** [comment]
pushed to master

**Pull request closed without merging**
