### PR TITLE
Teiid: Reflect commits from jbtis-4.2.x branch to master

### PR DESCRIPTION
**Pull request by mmakovy**

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
I added a small change which comes from new RedDeer 1.0.0.Final (usage of AbstractWaitCondition)

**Comment by apodhrad** [comment]
pushed to master

**Pull request merged**
