### PR TITLE
JBTIS-617 Fix ConnectionProfileHelper - add Vendor

### PR DESCRIPTION
**Pull request by mmakovy**
https://issues.jboss.org/browse/JBTIS-617

### CODE REVIEW

**Comment by mmakovy** [comment]
Please, push this also to jbtis-4.2.x branch

**Comment by vpakan** [comment]
Can one of the admins verify this patch?

**Comment by tsedmik** [comment]
test this

**Comment by tsedmik** [comment]
test this

**Comment by tsedmik** [comment]
looking

**Comment by tsedmik** [comment]
pushed to _master_

**Pull request closed without merging**
