### PR TITLE
ProcedurePreviewTest: changed CP, created project(source and view model)...

### PR DESCRIPTION
**Pull request by jdurani**
..., added MyTestUDF.jar; fixed parameters setting for UDF, procedure

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch?

**Comment by apodhrad** [comment]
please do not add binary files such as MyTestUdf-1.0-SNAPSHOT.jar to the repository

**Comment by apodhrad** [comment]
looking

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
pushed to master

**Pull request closed without merging**
