### PR TITLE
Teiid: add XmlStagingTableTest, update XmlSchemalessTest, CopyAndCloneTest (jbtis-4.2.x branch)

### PR DESCRIPTION
**Pull request by mmakovy**

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch?

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
@mmakovy there are compile errors

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.22.0:compile (default-compile) on project org.jboss.tools.teiid.ui.bot.test: Compilation failure: Compilation failure:
[ERROR] /home/apodhrad/Projects/jbosstools-integration-stack-tests/tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/XmlStagingTableTest.java:[251]
[ERROR] mgr.addModelsToVDB(PROJECT_NAME, vdbName, "SchemaModel.xmi");
[ERROR] ^^^^^^^^^^^^^^
[ERROR] The method addModelsToVDB(String, String, String[]) in the type VDBManager is not applicable for the arguments (String, String, String)

**Comment by mmakovy** [comment]
Compilation error should be fixed

**Pull request merged**
