### PR TITLE
Drools: update plugin version to 6.3.0.Final

### PR DESCRIPTION
**Pull request by tomasdavidorg**

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by apodhrad** [comment]
test this

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by tomasdavidorg** [comment]
Please merge this into master and 4.2.x after #525 is merged. Thanks.

**Comment by apodhrad** [comment]
pushed to master and jbtis-4.2.x

**Pull request closed without merging**
