### PR TITLE
Drools: Add drools support to runtime reddeer plugin

### PR DESCRIPTION
**Pull request by tomasdavidorg**

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch?

**Comment by tsedmik** [comment]
test this

**Comment by tsedmik** [comment]
verification job failed
- SmokeTests have to be runnable without specifying _-Dreddeer.config_ externally

```
org.jboss.reddeer.junit.configuration.RedDeerConfigurationException: The configuration location /home/jbossqa/workspace/jbtis.verification.test/31cc4d93/tests/org.jboss.tools.drools.ui.bot.test/${reddeer.config} does not exist
	at org.jboss.reddeer.junit.internal.configuration.SuiteConfiguration.getConfigurationFiles(SuiteConfiguration.java:72)
	at org.jboss.reddeer.junit.internal.configuration.SuiteConfiguration.getConfigurationFiles(SuiteConfiguration.java:67)
	at org.jboss.reddeer.junit.internal.configuration.SuiteConfiguration.findTestRunConfigurations(SuiteConfiguration.java:40)
	at org.jboss.reddeer.junit.internal.configuration.SuiteConfiguration.getTestRunConfigurations(SuiteConfiguration.java:31)
	at org.jboss.reddeer.junit.runner.RedDeerSuite.createSuite(RedDeerSuite.java:86)
	at org.jboss.reddeer.junit.runner.RedDeerSuite.<init>(RedDeerSuite.java:69)
	at org.jboss.reddeer.junit.runner.RedDeerSuite.<init>(RedDeerSuite.java:56)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:33)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:21)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:262)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:156)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:82)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:91)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:44)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable$1.run(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tomasdavidorg** [comment]
This hopefully fix the problem.

**Comment by tsedmik** [comment]
test this

**Comment by tsedmik** [comment]
pushed to master

**Pull request closed without merging**
