### PR TITLE
JBTIS-789: extend and modify project tests

### PR DESCRIPTION
**Pull request by tomasdavidorg**

### CODE REVIEW

**Comment by tomasdavidorg** [comment]
Do not merge. I have to fix some parts of the code.

**Comment by tomasdavidorg** [comment]
test this

**Comment by tomasdavidorg** [comment]
test this

**Comment by tomasdavidorg** [comment]
Now, it can be merged

**Comment by tsedmik** [comment]
looking

**Comment by tsedmik** [comment]
pushed to master

**Pull request closed without merging**
