### PR TITLE
SwitchYard: tests fail on deleting all projects

### PR DESCRIPTION
**Pull request by apodhrad**

### CODE REVIEW

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
test this

**Comment by tsedmik** [comment]
test this

**Comment by tsedmik** [comment]
pushed to master

**Pull request closed without merging**
