### PR TITLE
JBTIS-755, JBTIS-900: improve stability and skip broken drools tests

### PR DESCRIPTION
**Pull request by tomasdavidorg**
Drools: remove deprecated test

Drools: add skip condition for Drools-1336 issue

Drools: remove tests for unimplemented features

Drools: mark reported issues in DeclareCompletionTest

Drools: mark reported issue in MetadataCompletionTest

Drools: mark reported issue in RulesManagementTest

Drools: mark reported issues in DroolsRuntimeManagementTest

Drools: workaround for RHBRMS-713

Drools: mark reported issue in DslEditorTest

Drools: fix testGlobalUsageConsequence test with openjdk

Drools: make MavenProjectTest more stable

Drools: remove outdated todo and fixme comments

Drools: remove two unimportant constantly failing false positives test

Drools: stabilize CreateItemsRestTest

Drools: stabilize CreateItemsTest

### CODE REVIEW

**Comment by tomasdavidorg** [comment]
test this

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
test this

**Comment by tomasdavidorg** [comment]
test this

**Comment by tomasdavidorg** [comment]
test this

**Comment by tomasdavidorg** [comment]
Verification job is blue.

**Comment by apodhrad** [comment]
pushed to master

**Pull request closed without merging**
