### PR TITLE
BPMN2: fix ImportInterface test 4.2.x

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch? (use 'ok to test' comment to run verification job)

**Comment by apodhrad** [comment]
@jomarko could you check this PR once again, please? I think there's something wrong because it contains 98 commits

**Comment by apodhrad** [comment]
@jomarko probably you want to merge this PR to the branch jbtis-4.2.x and not into master

**Comment by jomarko** [comment]
@apodhrad of course, you are right, sorry for mistake

**Pull request closed without merging**
